[mysql]
host = "localhost"
port = 3306
database = "extjobs"
username = "root"
password = "toor"
table = "convert"
params = ["input", "output"]
params_filter = ["\\A[/_0-9A-Za-z.\\-]+\\z", "\\A[/_0-9A-Za-z.\\-]+\\z"]

[command]
template = "/usr/bin/avconv {{index . 0}} {{index . 1}}"
timeout = 300
workers = 2
shell = "/bin/sh"
