[mysql]
host = "localhost"
port = 3306
database = "videoconverter"
username = "root"
password = "toor"
table = "convert"
params = ["path"]

[command]
template = "/usr/bin/avconv {{index . 0}}"
timeout = 300
workers = 2
shell = "/bin/sh"
